<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class News extends Model
{
    //
    use SoftDeletes;

    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }

}
